### ISSUE TITLE
Memory allocation problem

### ISSUE THREAD

**Issue by tdiekel** [mahyarnajibi/SNIPER#127]
Hey all,

I currently fail to run training for my own dataset. I used the `train_neg_props_and_sniper.sh` script which works fine until the actual training starts. I always get `OSError: [Errno 12] Cannot allocate memory`, even though I tried to reduce `NUM_PROCESS` and `NUM_THREAD` to 2 as well as increasing `CHIPS_DB_PARTS` to 10000 and decreasing to 2. I'm not sure where else I can reduce memory consumption. 

Setup:
32 GB Ram
2x Geforce 1080 Ti

Dataset:
21510 images in 1280x720 with 187 classes

Config file:
```
# --------------------------------------------------------------
# SNIPER: Efficient Multi-Scale Training
# Licensed under The Apache-2.0 License [see LICENSE for details]
# by Mahyar Najibi, Bharat Singh
# --------------------------------------------------------------
---
MXNET_VERSION: "mxnet"
output_path: "./training/1.1_SNIPER"
symbol: resnet_mx_101_e2e
gpus: '0,1'
CLASS_AGNOSTIC: true
default:
  kvstore: device
network:
  pretrained: "./data/pretrained_model/resnet_mx_101_imgnet"
  pretrained_epoch: 0
  PIXEL_MEANS:
  - 118.37015144
  - 119.24320887
  - 118.89340919
  RPN_FEAT_STRIDE: 16
  FIXED_PARAMS:
  - conv0
  - bn0
  - stage1

  ANCHOR_RATIOS:
  - 0.5
  - 1
  - 2
  ANCHOR_SCALES:
  - 2
  - 4
  - 7
  - 10
  - 13
  - 16
  - 24
  NUM_ANCHORS: 21
dataset:
  NUM_CLASSES: 188
  dataset: coco
  dataset_path: "./data/01_Datasets/2018_Dez/02_COCO/75_20_5_Exclude"
  image_set: train2018
  root_path: "./data"
  test_image_set: val2018
  proposal: rpn
TRAIN:
  ## CHIP GENERATION PARAMS
  # Whether to use C++ or python code for chip generation
  CPP_CHIPS: true
  # How many parts the dataset should be divided to for parallel chip generation
  # This is used to keep the memory limited
  CHIPS_DB_PARTS: 10000 # Default: 20


  # Multi-processing params
  # These parameters are used for parallel chip generation, NMS, etc.
  # Please consider adjusting them for your system
  NUM_PROCESS: 2 # Default: 64
  NUM_THREAD: 2 # Default: 8

  # Whether to train with segmentation mask
  WITH_MASK: false

  # Training scales
  # The scales should be sorted in descending order based on size 
  # (the first scale is the highest resolution and the last scale is the lowest one)
  # Two types of scale definition are supported
  SCALES:
  # 1) You can define scale based on resolutions in pixels
  # [min_resolution, max_resolution]
  # The shortest side of the image is resized to min_resolution while the 
  # longest side is kept less than max_resolution
  # -1 indicates no constraint on min/max resolution
  - !!python/tuple [1400, 2000]
  - !!python/tuple [800, 1280]
  - !!python/tuple [-1, 512]
  
  # 2) Alternatively you can define the scaling factor as below:
  # In this case, the lowest resolution should be the maximum side of image
  # in pixels and all other scales should be defined as a float scaling factor
  # The following are the scales we used in the paper for COCO dataset
  # - 3.0
  # - 1.667
  # - 512.0



  # Valid ranges in each scale (boxes which the square root of their area
  # lie in each range are marked as valid in that scale).
  # Values indicate the square root of the area of boxes in
  # the **original** image resolution (before any scaling).
  # If the resolution of the images in your dataset is higher than COCO,
  # you can consider increasing these values based on the area distribution of
  # small, medium and large objects in the original resolution of your dataset.
  # -1 indicates having no constraint.
  VALID_RANGES:
  - !!python/tuple [-1,80]
  - !!python/tuple [32,150]
  - !!python/tuple [120,-1]


  lr: 0.0056 
  lr_step: '8,10'
  warmup: true
  fp16: true
  warmup_lr: 0.0005 
  wd: 0.0001
  scale: 100.0
  warmup_step: 1333
  begin_epoch: 0
  end_epoch: 13

  # whether flip image
  FLIP: true
  # whether shuffle image
  SHUFFLE: true
  # Number of images per GPU
  BATCH_IMAGES: 8
  # e2e changes behavior of anchor loader and metric
  END2END: true
  # R-CNN
  # rcnn rois batch size
  BATCH_ROIS: -1
  BATCH_ROIS_OHEM: 256
  # rcnn rois sampling params
  FG_FRACTION: 0.25
  FG_THRESH: 0.5
  BG_THRESH_HI: 0.5
  BG_THRESH_LO: 0.0
  # rcnn bounding box regression params
  BBOX_REGRESSION_THRESH: 0.5
  BBOX_WEIGHTS:
  - 1.0
  - 1.0
  - 1.0
  - 1.0

  # RPN anchor loader
  # rpn anchors batch size
  RPN_BATCH_SIZE: 256
  # rpn anchors sampling params
  RPN_FG_FRACTION: 0.5
  RPN_POSITIVE_OVERLAP: 0.5
  RPN_NEGATIVE_OVERLAP: 0.4
  RPN_CLOBBER_POSITIVES: false
  # rpn bounding box regression params
  RPN_BBOX_WEIGHTS:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  RPN_POSITIVE_WEIGHT: -1.0
  # used for end2end training
  # RPN proposal
  CXX_PROPOSAL: false
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 300
  RPN_MIN_SIZE: 0
  # approximate bounding box regression
  BBOX_NORMALIZATION_PRECOMPUTED: true
  BBOX_MEANS:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  BBOX_STDS:
  - 0.1
  - 0.1
  - 0.2
  - 0.2
TEST:
  # Maximum number of detections per image
  # Set to -1 to disable
  MAX_PER_IMAGE: 200

  # Whether to do multi-scale inference
  SCALES:
  - !!python/tuple [1400, 2000]
  - !!python/tuple [800, 1280]
  - !!python/tuple [480, 512]

  # Number of images per gpu for each scale
  BATCH_IMAGES:
  - 2
  - 2
  - 4

  # Number of concurrent jobs used for inference
  # if greater than 1, the roidb is distributed over
  # concurrent jobs to increase throughput
  CONCURRENT_JOBS: 2

  # Valid ranges in each scale (boxes which the square root of their area
  # lie in each range are marked as valid in that scale).
  # Values indicate the square root of the area of boxes in
  # the **original** image resolution (before any scaling).
  # If the resolution of the images in your dataset is higher than COCO,
  # you can consider increasing these values based on the area distribution of
  # small, medium and large objects in the original resolution of your dataset.
  # -1 indicates having no constraint.
  VALID_RANGES:
  - !!python/tuple [-1,90]
  - !!python/tuple [32,180]
  - !!python/tuple [75,-1]

  # Use rpn to generate proposal
  HAS_RPN: true

  # RPN Parameters
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 300
  RPN_MIN_SIZE: 0
  PROPOSAL_NMS_THRESH: 0.7
  PROPOSAL_PRE_NMS_TOP_N: 20000
  PROPOSAL_POST_NMS_TOP_N: 2000
  PROPOSAL_MIN_SIZE: 0

  # NMS Parameters
  # Whether to apply NMS based on threshold or sigma
  NMS: -1 #0.45
  NMS_SIGMA: 0.55

  # Which epoch of the training be used for testing
  TEST_EPOCH: 13

  # VISUALIZATION CONFIG
  VISUALIZATION_PATH: './debug/visualization'
  # Whether to visualize all intermediate scales
  # before aggregation (when doing multi-scale inference)
  # If False, only final detections are saved to 
  # VISUALIZATION_PATH
  VISUALIZE_INTERMEDIATE_SCALES: false

  # PROPOSAL EXTRACTION FLAGS
  # If true only would extract proposals
  EXTRACT_PROPOSALS: false

  # The folder path to be used for saving proposals
  PROPOSAL_SAVE_PATH: 'output/proposals'

  # Number of proposals extracted per scale
  # SCALES and BATCH_IMAGES above would be used to
  # Specify scales and number of images per batch for
  # each scale, no valid ranges would be applied for
  # aggregating proposals
  N_PROPOSAL_PER_SCALE: 300
```

Error log:
```
python main_train.py --cfg ./training/1.1_SNIPER/sniper_res101_e2e.yml --set proposal_path data/computed_proposals
/home/osm/machine_learning/SNIPER/configs/faster/default_configs.py:171: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
loading annotations into memory...
Done (t=0.20s)
creating index...
index created!
num_images 21510
COCO_train2018 gt roidb loaded from ./data/cache/COCO_train2018_gt_roidb.pkl
appending ground truth annotations
Reading cached proposals after ***NMS**** from data/computed_proposals/COCO_train2018_rpn_after_nms.pkl
Done!
append flipped images to roidb
filtered 3692 roidb entries: 43020 -> 39328
add bounding box regression targets
bbox target means:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]
bbox target stdevs:
[[0.1 0.1 0.2 0.2]
 [0.1 0.1 0.2 0.2]]
[0.1 0.1 0.2 0.2]
Creating Iterator with 39328 Images
Traceback (most recent call last):
  File "main_train.py", line 82, in <module>
    threads=config.TRAIN.NUM_THREAD, pad_rois_to=400)
  File "lib/iterators/MNIteratorE2E.py", line 31, in __init__
    self.pool = Pool(config.TRAIN.NUM_PROCESS)
  File "/home/osm/miniconda3/envs/sniper/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/home/osm/miniconda3/envs/sniper/lib/python2.7/multiprocessing/pool.py", line 161, in __init__
    self._repopulate_pool()
  File "/home/osm/miniconda3/envs/sniper/lib/python2.7/multiprocessing/pool.py", line 225, in _repopulate_pool
    w.start()
  File "/home/osm/miniconda3/envs/sniper/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/home/osm/miniconda3/envs/sniper/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

I would be glad for any suggestion.
